stages:
    - preprod
    - production

image: node:14-alpine

cache:
    paths:
        - node_modules/

preprod:
    stage: preprod
    only:
        - develop
    before_script:
        - npm i -g firebase-tools
        - npm install -g @angular/cli
        - npm install
    script:
        - firebase use dev --token "$FIREBASE_DEPLOY_KEY"
        - ng build --aot
        - firebase deploy --token "$FIREBASE_DEPLOY_KEY" --non-interactive --only hosting

production:
    stage: production
    only:
        - master
    before_script:
        - npm i -g firebase-tools
        - npm install -g @angular/cli
        - npm install
    script:
        - firebase use prod --token "$FIREBASE_DEPLOY_KEY"
        - ng build --prod
        - firebase deploy --token "$FIREBASE_DEPLOY_KEY" --non-interactive --only hosting
